// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const fs = require('fs')

const screenshots = "./test/screenshots/"

describe('Phylo.io Test Suite', function() {
  this.timeout(30000)
  let driver
  let vars

  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {

    if (this.currentTest.state === 'failed') {
      var t = this.currentTest.title
      driver.takeScreenshot().then(function(data){
        var base64Data = data.replace(/^data:image\/png;base64,/,"")
        fs.writeFile(screenshots + t + "|" + Date.now() + ".png", base64Data, 'base64', function(err) {
          if(err) console.log(err);
        });
      });
    }

    await driver.quit();
  })
  it('zoom-rescale-pan-zoomAt', async function() {
  })
  it('reroot-collapse', async function() {

    await driver.get("http://localhost:63342/phylo-io/phyloio/dist/index.html")
    await driver.manage().window().setRect(1401, 794)

    driver.executeScript("arguments[0].click();", driver.findElement(By.css("#master_g0 > .link:nth-child(4)")));
    driver.executeScript("arguments[0].click();", driver.findElement(By.css("#master_g0 > .node:nth-child(39) > .node")));
    driver.executeScript("arguments[0].click();", driver.findElement(By.css("#master_g1 > .link:nth-child(4)")));
    driver.executeScript("arguments[0].click();", driver.findElement(By.css("#master_g1 > .node:nth-child(46) > .node")));
    driver.executeScript("arguments[0].click();", driver.findElement(By.css("#master_g1 > .link:nth-child(5)")));

  })
  it('tree_toggle', async function() {
  })
})
